In [1]:
#import numpy library
import numpy as np

In [2]:
#create a list
l=[1,2,3,4,5,6]

In [3]:
#pass the list in numpy
#here it does not convert the element as a string bcz all the elements are numerical values
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
#1 dimensional array
#all types of data types are there
l1=[4,5,6,7,'sudh',34.356,True]

In [5]:
#in this case its converted every element inside l1 as string 
a1=np.array(l1)
a1

array(['4', '5', '6', '7', 'sudh', '34.356', 'True'], dtype='<U32')

In [6]:
#2 dimensional array
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#3 dimensional array
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
#check the dimension using ndim function
a1.ndim

1

In [9]:
#check the dimension
a2.ndim

2

In [10]:
#check the dimension
a3.ndim

3

In [11]:
#Try to tell us about total no. of elelments in a1
a1.size

7

In [12]:
#Try to tell us total no. of elelments in a2
a2.size

6

In [13]:
#Try to tell us total no. of elelments in a3
a3.size

9

In [14]:
#There is only 1 dim available
a1.shape

(7,)

In [15]:
# 2 rows 3 columns
a2.shape

(2, 3)

In [16]:
# 3 rows 3 columns
#we have 3x3 ,one such kind of matrices
a3.shape

(1, 3, 3)

In [17]:
a1

array(['4', '5', '6', '7', 'sudh', '34.356', 'True'], dtype='<U32')

In [18]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
#it will generate random no. between 2 to 5
np.random.randint(2,5)

3

In [21]:
#it will generate random no. between 2 to 50,and it will generate 3 rows and 4 column
np.random.randint(2,50,(3,4))

array([[15, 17, 15, 11],
       [45, 40, 39,  9],
       [44, 46, 36,  5]])

In [22]:
#it will generate random no. between 2 to 50,and it will generate 3 rows and 4 column have 2 such matrixes
np.random.randint(2,50,(2,3,4))

array([[[11,  3,  3, 25],
        [38, 30, 34, 32],
        [ 7, 11, 46, 12]],

       [[26, 12,  9, 31],
        [29, 10, 24, 35],
        [38, 29, 20,  6]]])

In [23]:
#if we have to generate any random mean and random standard deviation then we use 'rand'
np.random.rand(5,4)

array([[0.26492503, 0.03859155, 0.68584901, 0.08958051],
       [0.75230287, 0.06385058, 0.41540706, 0.10649157],
       [0.17793522, 0.36100963, 0.59375041, 0.86448681],
       [0.95493718, 0.41499963, 0.33250327, 0.96085056],
       [0.36355261, 0.43888195, 0.48940568, 0.50176683]])

In [24]:
#if we have to generate normal distribution then we use 'randn'
#normal distribution: mean=0, standard deviation=1
a4=np.random.randn(4,4)
a4

array([[ 1.13485187, -0.64616623, -0.29181539,  0.6589892 ],
       [-0.06387042, -0.45405154,  0.25546283,  0.6710187 ],
       [ 1.62852436,  0.01773605, -0.55623959,  1.10656133],
       [ 0.34282075, -0.18820682,  0.43883691,  0.84813753]])

In [25]:
#Changing Shape of Data (In Images, we crop the image)
#a4.reshape(3,4) #Error because this will accomodate 12 dataset points but we have 16 dataset points
a4.reshape(2,8)

array([[ 1.13485187, -0.64616623, -0.29181539,  0.6589892 , -0.06387042,
        -0.45405154,  0.25546283,  0.6710187 ],
       [ 1.62852436,  0.01773605, -0.55623959,  1.10656133,  0.34282075,
        -0.18820682,  0.43883691,  0.84813753]])

In [26]:
a4.reshape(8,2)

array([[ 1.13485187, -0.64616623],
       [-0.29181539,  0.6589892 ],
       [-0.06387042, -0.45405154],
       [ 0.25546283,  0.6710187 ],
       [ 1.62852436,  0.01773605],
       [-0.55623959,  1.10656133],
       [ 0.34282075, -0.18820682],
       [ 0.43883691,  0.84813753]])

In [48]:
a4.reshape(16,1)

array([[ 1.13485187],
       [-0.64616623],
       [-0.29181539],
       [ 0.6589892 ],
       [-0.06387042],
       [-0.45405154],
       [ 0.25546283],
       [ 0.6710187 ],
       [ 1.62852436],
       [ 0.01773605],
       [-0.55623959],
       [ 1.10656133],
       [ 0.34282075],
       [-0.18820682],
       [ 0.43883691],
       [ 0.84813753]])

In [28]:
##Since 2 is a factor of 16, -1 or any negative number means that 
#it will automatically detect the other factor which is 8 in this case
a4.reshape(2,-1)

array([[ 1.13485187, -0.64616623, -0.29181539,  0.6589892 , -0.06387042,
        -0.45405154,  0.25546283,  0.6710187 ],
       [ 1.62852436,  0.01773605, -0.55623959,  1.10656133,  0.34282075,
        -0.18820682,  0.43883691,  0.84813753]])

In [29]:
a4.reshape(2,-1345667)

array([[ 1.13485187, -0.64616623, -0.29181539,  0.6589892 , -0.06387042,
        -0.45405154,  0.25546283,  0.6710187 ],
       [ 1.62852436,  0.01773605, -0.55623959,  1.10656133,  0.34282075,
        -0.18820682,  0.43883691,  0.84813753]])

In [30]:
# 2 rows and 4 column , 2 such kind of array
a4.reshape(2,2,4)

array([[[ 1.13485187, -0.64616623, -0.29181539,  0.6589892 ],
        [-0.06387042, -0.45405154,  0.25546283,  0.6710187 ]],

       [[ 1.62852436,  0.01773605, -0.55623959,  1.10656133],
        [ 0.34282075, -0.18820682,  0.43883691,  0.84813753]]])

In [31]:
#make sure multiplication of all of the no. must be equal to total no. we have , here in this case our total no. is 16
a4.reshape(1,1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[[ 1.13485187, -0.64616623, -0.29181539,
                  0.6589892 ],
                [-0.06387042, -0.45405154,  0.25546283,
                  0.6710187 ]],

               [[ 1.62852436,  0.01773605, -0.55623959,
                  1.10656133],
                [ 0.34282075, -0.18820682,  0.43883691,
                  0.84813753]]]]]]]]]]])

In [32]:

a1

array(['4', '5', '6', '7', 'sudh', '34.356', 'True'], dtype='<U32')

In [33]:
#Slicing is Exactly similar to list
a1[0]

'4'

In [34]:
a1[2:6]

array(['6', '7', 'sudh', '34.356'], dtype='<U32')

In [35]:
#giving step size here
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [36]:
#can reverse also
a1[::-1]

array(['True', '34.356', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [37]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [38]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
#it will return 1st row
a2[0]

array([1, 2, 3])

In [40]:
#:means give all row and 1: means starting from column 1 till end
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [41]:
#other way to extract the data
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [42]:
#other way to extract the data
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [43]:
#it will generate random no. between 2 to 90,and it will generate 6 rows and 5 column
a5=np.random.randint(2,90,(6,5))
a5

array([[79, 55, 89, 23, 28],
       [83, 75, 87, 66, 33],
       [10, 19, 30,  5, 56],
       [57, 73, 35, 80,  3],
       [37, 23, 62, 65, 73],
       [22, 64, 81, 69, 24]])

In [44]:
#filter out all the record which is having value >40
a5[a5>40]

array([79, 55, 89, 83, 75, 87, 66, 56, 57, 73, 80, 62, 65, 73, 64, 81, 69])

In [45]:
a5

array([[79, 55, 89, 23, 28],
       [83, 75, 87, 66, 33],
       [10, 19, 30,  5, 56],
       [57, 73, 35, 80,  3],
       [37, 23, 62, 65, 73],
       [22, 64, 81, 69, 24]])

In [46]:
#change the value to 100 at position row 0 column 1
a5[0,1]=100

In [47]:
a5

array([[ 79, 100,  89,  23,  28],
       [ 83,  75,  87,  66,  33],
       [ 10,  19,  30,   5,  56],
       [ 57,  73,  35,  80,   3],
       [ 37,  23,  62,  65,  73],
       [ 22,  64,  81,  69,  24]])

In [49]:
#it will generate random no. between 0 to 3,and it will generate 3 rows and 3 column
a6 = np.random.randint(0,3 , (3,3))

In [50]:
#it will generate random no. between 0 to 3,and it will generate 3 rows and 3 column
a7 = np.random.randint(0,3 , (3,3))

In [51]:
a6

array([[1, 2, 2],
       [0, 2, 1],
       [0, 1, 1]])

In [52]:
a7

array([[0, 0, 1],
       [2, 0, 0],
       [2, 1, 2]])

In [53]:
#Element Wise Multiplication and not Matrix Multiplication
a6*a7

array([[0, 0, 2],
       [0, 0, 0],
       [0, 1, 2]])

In [54]:
#matrix multiplication
a6@a7

array([[8, 2, 5],
       [6, 1, 2],
       [4, 1, 2]])

# if there is 2x2 and a 2x3 matrix is there and we have to do matrix multiplication:
    Note:
        -our final matrix woulbe 2x3 
        -matrix multiplication is possible if 1st matrix col. value and 2nd matrix row value is same.here in this case it is 2

In [55]:
a6

array([[1, 2, 2],
       [0, 2, 1],
       [0, 1, 1]])

In [56]:
#Array Operations
a6+100

array([[101, 102, 102],
       [100, 102, 101],
       [100, 101, 101]])

In [57]:
a6*2

array([[2, 4, 4],
       [0, 4, 2],
       [0, 2, 2]])

In [58]:
#No Errors in case numpy
a6/0

C:\Users\ABHANJ~1\AppData\Local\Temp/ipykernel_7920/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\ABHANJ~1\AppData\Local\Temp/ipykernel_7920/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [nan, inf, inf],
       [nan, inf, inf]])

In [59]:
a6**3

array([[1, 8, 8],
       [0, 8, 1],
       [0, 1, 1]], dtype=int32)

In [62]:
#zero function is used to create o matrix
a8 = np.zeros((4,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
#zero function is used to create o matrix
a9 = np.ones((4,5))
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [65]:
#Doing row by row operation. Also called as Broadcasting operation
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [66]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
#as no. of row element is 5 and we are trying to add with 4 no.s only so throwing error
a9+np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [71]:
#How to do column wise Boradcasting operation: We will have to transpose first and then add
#np.array([1,2,3,4]).T + a9   
#Error because for transpose we need 2 dimesnsions. Hence we will give 2 brackets to convert into 2d
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [72]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [73]:
#Understanding Transpose
print(a6)
print(a6.T)

[[1 2 2]
 [0 2 1]
 [0 1 1]]
[[1 0 0]
 [2 2 1]
 [2 1 1]]


In [75]:
a5

array([[ 79, 100,  89,  23,  28],
       [ 83,  75,  87,  66,  33],
       [ 10,  19,  30,   5,  56],
       [ 57,  73,  35,  80,   3],
       [ 37,  23,  62,  65,  73],
       [ 22,  64,  81,  69,  24]])

In [76]:
#square root of element
np.sqrt(a5)

array([[ 8.88819442, 10.        ,  9.43398113,  4.79583152,  5.29150262],
       [ 9.11043358,  8.66025404,  9.32737905,  8.1240384 ,  5.74456265],
       [ 3.16227766,  4.35889894,  5.47722558,  2.23606798,  7.48331477],
       [ 7.54983444,  8.54400375,  5.91607978,  8.94427191,  1.73205081],
       [ 6.08276253,  4.79583152,  7.87400787,  8.06225775,  8.54400375],
       [ 4.69041576,  8.        ,  9.        ,  8.30662386,  4.89897949]])

In [77]:
#exponential of the element
print(np.exp(a5))

[[2.03828107e+34 2.68811714e+43 4.48961282e+38 9.74480345e+09
  1.44625706e+12]
 [1.11286375e+36 3.73324200e+32 6.07603023e+37 4.60718663e+28
  2.14643580e+14]
 [2.20264658e+04 1.78482301e+08 1.06864746e+13 1.48413159e+02
  2.09165950e+24]
 [5.68572000e+24 5.05239363e+31 1.58601345e+15 5.54062238e+34
  2.00855369e+01]
 [1.17191424e+16 9.74480345e+09 8.43835667e+26 1.69488924e+28
  5.05239363e+31]
 [3.58491285e+09 6.23514908e+27 1.50609731e+35 9.25378173e+29
  2.64891221e+10]]


In [78]:
#logarithimic of the element
print(np.log10(a5))

[[1.89762709 2.         1.94939001 1.36172784 1.44715803]
 [1.91907809 1.87506126 1.93951925 1.81954394 1.51851394]
 [1.         1.2787536  1.47712125 0.69897    1.74818803]
 [1.75587486 1.86332286 1.54406804 1.90308999 0.47712125]
 [1.56820172 1.36172784 1.79239169 1.81291336 1.86332286]
 [1.34242268 1.80617997 1.90848502 1.83884909 1.38021124]]


In [84]:
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [85]:
#print(list(range(0,10,2.5))) #Error because jump size cannot be float
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [86]:
#Arange same as range but it also takes jump size as float
print(np.arange(10))
print(np.arange(1.8,10.7,2.5))

[0 1 2 3 4 5 6 7 8 9]
[1.8 4.3 6.8 9.3]


In [88]:
#it is used if In between certain range, we want to generate numbers
print(np.linspace(2,3,num=50)) #Considers Linear Spac

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]


In [89]:
print(np.linspace(2,3,num=50,retstep=True)) 
#retstep:return Jumpsize

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]), 0.02040816326530612)


In [90]:
np.logspace(2,4,num=4,base=10) 
#Considers Logarithmic Base

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [91]:
#Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])